Requirement already satisfied: python-dateutil in c:\users\danand\anaconda3\envs\gnn\lib\site-packages (2.8.2)
Requirement already satisfied: six>=1.5 in c:\users\danand\appdata\roaming\python\python39\site-packages (from python-dateutil) (1.16.0)
